#!/bin/bash

#This script is validating a password strength

#Get password
echo "Password verification starts..."
pass=${*}

#Configure colors for output
red=$'\e[0;31m'
green=$'\e[1;32m'
reset=$'\e[0m'

#Check if password has at least 10 digits
if test ${#pass} -ge 10 ; then
    #Check if password has numbers
    echo $pass | grep -q [0-9]
    if test $? -eq 0 ; then
        #Check if password has lower letter
        echo $pass | grep -q [a-z]
        if test $? -eq 0 ; then
            #Check if password has capital letter
            echo $pass | grep -q [A-Z]   
            if test $? -eq 0 ; then
                echo "$green Password is strong $reset"
                exit 0;
            else
                echo "$red There must be at least ona capital letter in the password $reset"
                exit 1;
            fi
        else
            echo "$red There must be at least one lower letter in the password $reset"
            exit 1;
        fi
    else
        echo "$red There must be at least one number in the password $reset"
        exit 1;
    fi
else
    echo "$red There are less then 10 digits in the password $reset"
    exit 1;
fi